---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.php"
  - "**.js"
exclude_paths:
- tests/
- assets/
- "twig/cache/**/*"
- "**/vendor/**/*"
